delete from figure_viewer_figureviewertopic;
delete from figure_viewer_modeofvariabilityinput ;
delete from figure_viewer_activitystate;
delete from figure_viewer_inputcombination;
delete from figure_viewer_animationinput;
delete from figure_viewer_seasoninput;
delete from figure_viewer_climatevariableinput;